### PR TITLE
.NET version upgrades and various other bits

### PR DESCRIPTION
**Pull request by ndalchau**
I started work on this branch a few months back, but didn't complete the work. 

1. Updates tools
2. Bumps up the version of .NET core
3. Better handling of filenames

Since then, I've done the following:

4. Enable sundials simulations with callback mechanism, so that incremental UI updates occur during long-running simulations. This also unifies sundials with the API of the other simulators.
5. Fixed build error of CRNEngineTSWrapper_Samples when relying on NodeJs.redist (provide hint for location, equivalent to other projects).

### CODE REVIEW

**Comment by ndalchau** [comment]
Anyone fancy doing a code review for me please? @ph1ll1ps , @cgravill , @PrashantVaidyanathan ?

**Comment by ph1ll1ps** [comment]
Sandra and I are in Mauritius for the next couple of weeks :-) You're welcome to merge without review if needed.

Best wishes,
Andrew

**Comment by cgravill** [comment]
Looks good generally.

I don't remember why we need .NET Core 2.1.* as well as 3.1.* though I seem to remember I did that. No chance of getting rid of that? Given NET Core 2.1.* is well out of support? I had a quick look previously at moving it all up to .NET Core 6.* but various dependencies got messy, perhaps I can try again after this one.

**Review by cgravill — APPROVED** [review]

**Comment by cgravill** [comment]
Oh and nice you've got the callbacks in for Sundials.

**Comment by ndalchau** [comment]
Fantastic, thanks both of you. @cgravill , trying to remoe 2.1 would definitely be a step forward. 

I've also been working on building with net 6.0 on linux. This actually works fine when removing SUNDIALs from the mix, and not attempting to run the tests... (e.g. via `dotnet test`). More on that in a future PR.

**Pull request merged**
