### PR TITLE
Remove .NET Core 2.1 workaround

### PR DESCRIPTION
**Pull request by cgravill**
There's a workaround for the build definitions to install .NET Core 2.1 as otherwise WebSharper fails with:
`error MSB6006: "wsfsc.cmd" exited with code -2147450730`

I've updated WebSharper to 4.7.* which is the latest version before some breaking changed. Specifically the later versions apparently drop `netstandard2.0` support -
https://github.com/dotnet-websharper/core/releases/tag/5.0.0.100-preview1

However, updating WebSharper creates a problem with external dependencies that are built with the version of WebSharper currently in this repository:
`Binary format version mismatch, found '4.5', expecting '4.7'`

I've worked around that by forking and inlining the relevant parts of
https://github.com/predictionmachines/FSharpIDD
https://github.com/SynBioDex/fSBOL

Options:
1. take the win, merge this
2. try to get the dependent projects to upgrade first (I think one is potentially easy to convince :wave: @PrashantVaidyanathan but the other isn't currently maintained so may need forking)
3. abandon this, put a note in the build files and link here
4. ???

### CODE REVIEW

**Comment by ndalchau** [comment]
Looks like a nice win! 

Inlining IDD makes sense to me, but let's see what @PrashantVaidyanathan says about FSBOL before making a decision on that bit.

**Comment by cgravill** [comment]
Update the current versions of WebSharper do support `netstandard2.0` I had misunderstood the changenote. So we can potentially upgrade that too. If @PrashantVaidyanathan doesn't object I'm inclined to go with inlining the dependencies to make any further updates simpler.

**Comment by PrashantVaidyanathan** [comment]
Sorry for the delay on my end. This looks great - and I agree inclining dependencies makes it easier going forward.  No objections on my end :)

**Review by ndalchau — DISMISSED** [review]

**Comment by ndalchau** [comment]
Is FSharp.IDD needed in paket.dependencies anymore? Same for FSBOL.

**Comment by ndalchau** [comment]
I've revised my opinion. Currently, SBOL isn't properly plumbed in to the code. It's commented out. So, I think a better solution here would be to not inline FSBOL at all, but instead comment out all paket references to it, and comment out any lingering references. I had a quick go at this on your Fork, @cgravill , and it seems to work. Shall I submit a PR to your fork, or just create a new PR here?

**Comment by cgravill** [comment]
On my fork `FSharpIDD.WS` wouldn't be needed. However, 'FSharpIDD' is still used. We could go further and have the non-WebSharper versions also used the inlined code. That would make it easier to change code if it's needed but that wasn't directly a goal of mine - just to diagnose and fix the immediate problem. Ideally any changes would flow back through IDD but I don't know if that's realistic.

@ndalchau as part of the pull request I think I gave any maintainers on this rights to directly edit on my fork. Go ahead with the dropping of FSBOL directly, or you can do a PR if needed.

**Comment by ndalchau** [comment]
> However, 'FSharpIDD' is still used. We could go further and have the non-WebSharper versions also used the inlined code.

This is exactly what I thought we should do.

> Ideally any changes would flow back through IDD but I don't know if that's realistic.

I agree, but also think that's unrealistic.

I don't have access to your Fork, so I'll make a new one, and raise a PR to yours.

**Comment by cgravill** [comment]
Merged your changes, can let this one build then merge @ndalchau

**Review by ndalchau — APPROVED** [review]

**Comment by cgravill** [comment]
I haven't run this with the additional changes but think it's good to go in.

**Pull request merged**
